##Creating a loop that will determine the relative enrichment of toxprints
#across all aeids in the toxcast holdings

# http://stats.stackexchange.com/questions/10328/using-rs-phyper-to-get-the-probability-of-list-overlap
# http://stackoverflow.com/questions/8382806/r-hypergeometric-test-phyper

# http://r.789695.n4.nabble.com/hypergeometric-vs-fisher-test-td2324223.html
# http://stackoverflow.com/questions/8382806/r-hypergeometric-test-phyper
# https://en.wikipedia.org/wiki/Fisher%27s_exact_test
# http://marray.economia.unimi.it/2009/material/lectures/L8_Gene_Set_Testing.pdf

rm(list=ls())
library(tcpl)
###################################################
tcplConf(drvr = "MySQL",
            user = "kconnors",
            pass = "pass",
            host = "134.67.216.113",
            db   = "prod_external_invitrodb_v2", 
            int  = TRUE)
###################################################

##Loading hitc matrix from external_v2
hitc <- tcplVarMat(var="hitc", only.public=TRUE)
cns <- colnames(hitc)
rnw <- rownames(hitc)
tested <- tcplVarMat(var="tested", only.public=TRUE)
tested <- tested[rnw, cns]

#set chnms tested in sc, but not mc to an inactive hitc (will have an "na" in the hitc matrix, now a 0)
hitc[tested==1 & is.na(hitc)] <- 0 

d <- as.data.table(hitc)
d[, code := rownames(hitc)]

chem.details <- tcplLoadChem()
chem.details <- unique(chem.details[, list(chid, chnm, code)])
setkey(d, "code")
setkey(chem.details, "code")

d <- chem.details[d]

##Bring in the ToxPrint file generated by M.Martin
toxprint <- as.data.table(read.csv("L:/Lab/NCCT_ToxCast/Connors/3. ACEA/4. AR analysis/ToxPrint_18960_729Frag_Matrix_COMPLETE_2014JAN07.csv"))
toxprint[, GSID := as.integer(sapply(strsplit(as.character(toxprint$DSSTox_GSID), "_"), "[[", 3))]
toxprint <- toxprint[, !grep("DSSTox|TS_ChemName", names(toxprint)), with=FALSE]

grps <- names(d)
grps <- grps[!grepl("chid|chnm|code", grps)]
  

chemotype <- data.table()

for(grp in grps){
  x.try <- d[, c("chid", grp), with=FALSE]
  x.try <- na.omit(x.try) #removes NA - chnms not tested
  x.try <- x.try[chid %in% toxprint$GSID, ] #subset to chnms that have chemotypes
  
  chnm.sum <- dim(x.try)[1]
  chnm.active.sum <- length(which(x.try==1)) #finds hitc==1 
  
  tp.all <- toxprint[GSID %in% x.try$chid, ] #subset toxprints to GSIDs shared by grp aeid
  tp.all <- tp.all[, !grep("GSID", names(tp.all)), with=FALSE] #remove the GSID column
  # tp.all[, lapply(.SD, sum)] #gives the chemotypes for all chems
  tp.sums <- colSums(tp.all)
  # tp.active <- toxprint[GSID %in% x.try[]]
  
  tp.act <- toxprint[GSID %in% x.try[get(grp)==1, chid], ] # d[get(grp)==1, .(chid)]
  tp.act <- tp.act[, !grep("GSID", names(tp.act)), with=FALSE] #remove the GSID column
  tp.act.sums <- colSums(tp.act)
  
  dat <- data.table(aenm=grp, 
                    ct_id=names(tp.sums),
                    tested.chnm=chnm.sum,
                    active.chnm=chnm.active.sum,
                    ct.all=tp.sums,
                    ct.act=tp.act.sums,
                    db.vers="prod_external_invitrodb_v2")
  
  chemotype <- rbind(chemotype, dat)
}

##This code provides the same answer as the fisher.test, but for clarity and 
#       transparency, I will use the fisher.test() function. 
# chemotype[, pval := phyper(ct.act-1, ct.all, tested.chnm-ct.all, active.chnm, lower.tail=FALSE, log.p=FALSE)]

chemotype <- chemotype[ct.all!=0, ] #ct_id where there are no chnms

chemotype[, c("pval", "odds.ratio"):= fisher.test(matrix(c(ct.act, 
                                                           ct.all-ct.act, 
                                                           active.chnm-ct.act, 
                                                          tested.chnm-active.chnm-(ct.all-ct.act)),
                                                          2, 2), 
                                                  alternative = "greater")[c("p.value", "estimate")],
          by=list(aenm, ct_id)]


library(fmsb)
OR.funct <- function(ct.act, ct.all, active.chnm, tested.chnm) {
  foo <- oddsratio(ct.act, 
                   ct.all-ct.act, 
                   active.chnm-ct.act, 
                   tested.chnm-active.chnm-(ct.all-ct.act),
                   conf.level = 0.95)
  return(as.list(c(as.vector(foo$conf.int), foo$p.value)))
}


chemotype[, c("OR95CI.low", "OR95CI.high", "ORpval") := 
            OR.funct(ct.act, ct.all, active.chnm, tested.chnm), by=list(aenm, ct_id)] 

chemotype[, Yules.Q := (odds.ratio - 1)/(odds.ratio + 1)]


#Note: Yule's Q ranges from -1 to 1, where 0 means there is no association
#   Accordig to "Social Research Methods: Qualitative and Quantitative" By Harvey Russell Bernard, 2000,
#   There is a citation for "Davies, 1971" stating:
#    Q=0, no assoc.
#    abs(Q): 0 - 0.29, small, negligible effect
#    abs(Q): 0.30-0.49, "moderate" assoc
#    abs(Q): 0.50-0.69, "substancial" assoc
#    abs(Q): >0.70, "very strong" assoc



###For Kristin's analysis only
# The utility of this logic should be verified for each application.
chemotype[, pos.enrich := 0]
chemotype[pval<0.005 & abs(Yules.Q)>0.3 & ORpval<0.05, pos.enrich := 1]









# ##This script can be used to create the chemotype matrix for invitrodb_internal_stable
# ##   Note: These values MAY NOT be stable. Check with the owner of the data before
# ##      using these results.
# 
# ##Pull in internal_stable db version. Note: my ACEA ER/AR data is not updated here
# ###################################################
# tcplConf(drvr = "MySQL",
#          user = "kconnors",
#          pass = "pass",
#          host = "134.67.216.113",
#          db   = "prod_internal_invitrodb_v2", 
#          int  = TRUE)
# ###################################################
# 
# ##Need a chemical hitc matrix for all aeids for invitrodb_v1, invitrodb_v2, and 
# ##  prod_internal_invitrodb_v2
# 
# ##For simplicity, I am loading a previous hitc matrix that is publically available.
# hitc <- tcplVarMat(var="hitc", only.public=FALSE)
# cns <- colnames(hitc)
# rnw <- rownames(hitc)
# tested <- tcplVarMat(var="tested", only.public=FALSE)
# tested <- tested[rnw, cns]
# 
# #set chnms tested in sc, but not mc to an inactive hitc (will have an "na" in the hitc matrix, now a 0)
# hitc[tested==1 & is.na(hitc)] <- 0 
# 
# d <- as.data.table(hitc)
# d[, code := rownames(hitc)]
# 
# 
# chem.details <- tcplLoadChem()
# chem.details <- unique(chem.details[, list(chid, chnm, code)])
# setkey(d, "code")
# setkey(chem.details, "code")
# 
# d <- chem.details[d]
# 
# ##Bring in the ToxPrint file generated by M.Martin
# toxprint <- as.data.table(read.csv("L:/Lab/NCCT_ToxCast/Connors/3. ACEA/4. AR analysis/ToxPrint_18960_729Frag_Matrix_COMPLETE_2014JAN07.csv"))
# toxprint[, GSID := as.integer(sapply(strsplit(as.character(toxprint$DSSTox_GSID), "_"), "[[", 3))]
# toxprint <- toxprint[, !grep("DSSTox|TS_ChemName", names(toxprint)), with=FALSE]
# 
# grps <- names(d)
# grps <- grps[!grepl("chid|chnm|code", grps)]
# 
# chemotype2 <- data.table()
# for(grp in grps){
#   x.try <- d[, c("chid", grp), with=FALSE]
#   x.try <- na.omit(x.try) #removes NA - chnms not tested
#   x.try <- x.try[chid %in% toxprint$GSID, ] #subset to chnms that have chemotypes
#   
#   chnm.sum <- dim(x.try)[1]
#   chnm.active.sum <- length(which(x.try==1)) #finds hitc==1 
#   
#   tp.all <- toxprint[GSID %in% x.try$chid, ] #subset toxprints to GSIDs shared by grp aeid
#   tp.all <- tp.all[, !grep("GSID", names(tp.all)), with=FALSE] #remove the GSID column
#   # tp.all[, lapply(.SD, sum)] #gives the chemotypes for all chems
#   tp.sums <- colSums(tp.all)
#   # tp.active <- toxprint[GSID %in% x.try[]]
#   
#   tp.act <- toxprint[GSID %in% x.try[get(grp)==1, chid], ] # d[get(grp)==1, .(chid)]
#   tp.act <- tp.act[, !grep("GSID", names(tp.act)), with=FALSE] #remove the GSID column
#   tp.act.sums <- colSums(tp.act)
#   
#   dat <- data.table(aenm=grp, 
#                     ct_id=names(tp.sums),
#                     tested.chnm=chnm.sum,
#                     active.chnm=chnm.active.sum,
#                     ct.all=tp.sums,
#                     ct.act=tp.act.sums,
#                     db.vers="prod_internal_invitrodb_v2")
#   
#   chemotype2 <- rbind(chemotype2, dat)
# }
# 
# 
# ##This code provides the same answer as the fisher.test, but for clarity and 
# #       transparency, I will use the fisher.test() function. 
# # chemotype[2, pval := phyper(ct.act-1, ct.all, tested.chnm-ct.all, active.chnm, lower.tail=FALSE, log.p=FALSE)]
# 
# chemotype2 <- chemotype2[ct.all!=0, ] #ct_id where there are no chnms
# 
# chemotype2[, c("pval", "odds.ratio"):= fisher.test(matrix(c(ct.act, 
#                                                            ct.all-ct.act, 
#                                                            active.chnm-ct.act, 
#                                                            tested.chnm-active.chnm-(ct.all-ct.act)),
#                                                          2, 2), 
#                                                   alternative = "greater")[c("p.value", "estimate")],
#           by=list(aenm, ct_id)]
# 
# library(fmsb)
# OR.funct <- function(ct.act, ct.all, active.chnm, tested.chnm) {
#   foo <- oddsratio(ct.act, 
#                    ct.all-ct.act, 
#                    active.chnm-ct.act, 
#                    tested.chnm-active.chnm-(ct.all-ct.act),
#                    conf.level = 0.95)
#   return(as.list(c(as.vector(foo$conf.int), foo$p.value)))
# }
# 
# chemotype2[, c("OR95CI.low", "OR95CI.high", "ORpval") := 
#             OR.funct(ct.act, ct.all, active.chnm, tested.chnm), by=list(aenm, ct_id)] 
# 
# chemotype2[, Yules.Q := (odds.ratio - 1)/(odds.ratio + 1)]



